### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by leonardopedroso** [fatosmorina/machine-learning-exams#1]
Stanford University, CS230 Deep Learning, Winter Quarter 2018: links to "Midterm Exam" and "Solution" are broken.

**Comment by leonardopedroso** [comment]
[This pull request](https://github.com/fatosmorina/machine-learning-exams/pull/2) addresses this issue.

**Comment by fatosmorina** [comment]
@leonardopedroso Thanks a lot. I really appreciate your help. I just merged the Pull Request.
